version: "3.9"
services:
  db:
    restart: always
    container_name: "mysql_db"
    image: mysql:8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: best_library
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - library-app
networks:
  library-app:
    driver: bridge

volumes:
  db_volume: